# Generated by Django 4.1.5 on 2023-03-24 13:38

from django.db import migrations, models
import video.validators


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='video/%y%M', validators=[video.validators.file_size]),
        ),
    ]
