# Generated by Django 4.1.5 on 2023-03-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_video_video_analyse'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyse',
            name='suggestie',
            field=models.TextField(blank=True),
        ),
    ]
