# Generated by Django 4.1.5 on 2023-03-23 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bleep', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interesantelink',
            options={'ordering': ['-gepubliceerd']},
        ),
        migrations.AddField(
            model_name='interesantelink',
            name='gepubliceerd',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum gepubliceerd'),
        ),
    ]
