# Generated by Django 4.1.5 on 2023-02-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_article_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleseries',
            name='publish',
            field=models.BooleanField(default=False),
        ),
    ]
