# Generated by Django 4.1.5 on 2023-02-27 14:59

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_articleseries_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='default/noimage.jpg', max_length=255, upload_to=main.models.Article.image_upload_to),
        ),
        migrations.AddField(
            model_name='articleseries',
            name='image',
            field=models.ImageField(default='default/noimage.jpg', max_length=255, upload_to=main.models.ArticleSeries.image_upload_to),
        ),
    ]
